### ISSUE TITLE
an error has occured 

### ISSUE THREAD

**Issue by Rozzla** [darmuh/ghostCodes#1]
(( French google translate /!\ ))

Hello Darmuh, 

Thank you for this incredible plugin which works perfectly, at least for version 1.1.1

I made a set of mods that work in vanilla without players needing to install anything, since you updated your mod to 1.5.0 it is impossible for players to join the game :

![image](https://github.com/darmuh/ghostCodes/assets/20723976/3d27980c-d4e5-4b04-9bfb-1ee2548d6744)

in console : [Netcode] NetworkConfig mismatch. The configuration between the server and client does not match

So for the moment I managed to put back the old version which still works with V49 but it would be super cool to be able to use 1.5.0 in vanilla like the old one ;)

Is it possible for you to make version 1.5.0 compatible in vanilla like the later version?

Thank you in advance for reading

AllZ0R.

**Comment by darmuh** [comment]
> (( French google translate /!\ ))
> 
> Hello Darmuh,
> 
> Thank you for this incredible plugin which works perfectly, at least for version 1.1.1
> 
> I made a set of mods that work in vanilla without players needing to install anything, since you updated your mod to 1.5.0 it is impossible for players to join the game :
> 
> ![image](https://private-user-images.githubusercontent.com/20723976/296298425-3d27980c-d4e5-4b04-9bfb-1ee2548d6744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTg4NDIsIm5iZiI6MTcwNTE5ODU0MiwicGF0aCI6Ii8yMDcyMzk3Ni8yOTYyOTg0MjUtM2QyNzk4MGMtZDRlNS00YjA0LTliZmItMWVlMjU0OGQ2NzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDAyMTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYmM0NDZlZmM3YTE4Y2I0MWM3ZTQxNTQ0ODUzMzFjN2Q4MzNkNjQyMDY4ZmVlYWY3ZWM2ODQ0NzQxNGYxMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.80lL0d2bzKI7AWQeS1oQs3tlD1KoXc9xIJYx2emiU-M)
> 
> in console : [Netcode] NetworkConfig mismatch. The configuration between the server and client does not match
> 
> So for the moment I managed to put back the old version which still works with V49 but it would be super cool to be able to use 1.5.0 in vanilla like the old one ;)
> 
> Is it possible for you to make version 1.5.0 compatible in vanilla like the later version?
> 
> Thank you in advance for reading
> 
> AllZ0R.

So this error occurs because you have networking enabled. You'll need to go to your config and disable networking via this configuration option:

![image](https://github.com/darmuh/ghostCodes/assets/152580271/dd97007f-a0d6-4f01-8773-3d1684c6cf86)

If you're not using a mod manager it is this option:
![image](https://github.com/darmuh/ghostCodes/assets/152580271/53bd2e10-0515-4b5f-868d-434029530b94)

I would 100% recommend upgrading to 1.5 not just for the new features (even though disabling networking does disable some things) but also as the code has been improved quite a bit from 1.1

I'll leave this issue open just so others can see the answer, as this is a common question being asked.

**Comment by darmuh** [comment]
if you still have issues hosting vanilla lobbies with networking disabled feel free to let me know 👍

**Comment by darmuh** [comment]
added to thunderstore wiki, closing this ticket
