### ISSUE TITLE
Ghost Girl sounds over walkie-talkie

### ISSUE THREAD

**Issue by GrumbleGrits** [darmuh/ghostCodes#12]
With this new addition I've found that using certain sound replacement mods make for a very... unenjoyable experience. I've noticed two particular issues.

- They sounds play over walkie-talkies that are off, unsure if this is intended...(issue persists even with sound replacement mods and other walkie mods disabled)
- Sound replacement mods, unsurprisingly, change the sound that comes through the walkie talkie.

These two things, alone, aren't too bad... unless the sound replacement someone is using has a really long sound file such as that of the Amber Alert mod. Is there any chance you could either: A, only play the sound over Walkie-Talkies that are ON, or B, copy and rename the sound file into the mod itself so it doesn't get replaced whenever it is played?(perhaps with config option to use original, allowing sound replacement to occur as normal?)

Could option B also be applied to the sounds through the terminal? having Amber Alerts overlapping through it is murderous on the ears and it would be some nice options to have. :)

**Comment by darmuh** [comment]
I've definitely wanted to implement Option B, maybe even with custom sounds rather than the vanilla ghost girl but have been limited by my own knowledge. Still working to implement this option at some point in the future, will just take some learning on my side.

As for Option A:
I think sounds _should_ only play on walkies that are turned on. I will look into this and try to fix it

**Comment by darmuh** [comment]
This issue should be fixed in 2.5.0, if you experience any further issues please post under a new issue
