### ISSUE TITLE
[Question] With GhostGirlEnhanced Mode, would the ghost codes only happen when the ghost girl spawns?

### ISSUE THREAD

**Issue by haroelim** [darmuh/ghostCodes#4]
On moons not listed in the GGEbypassList, do the ghost codes only get sent when the ghost girl spawns, or do they happen all the time?

What I wanted was the ghost codes to start occurring as an indication that someone is being haunted. Is that currently possible? (If not could I make that suggestion)

Edit: I just saw this in the description:
> BETA: Ghost Girl Enhanced Mode (enabled by default) will send codes ONLY when a ghost girl has spawned on the level and is actively hunting someone.

So follow up Question: If I want the ghostcodes to NOT happen on moons where she doesn't spawn, could I leave the GGEbypasslist empty, since the ghost girl doesn't spawn on those moons?

**Comment by darmuh** [comment]
if you have GGEBypass enabled, ghostcodes will fallback to insanity mode or normal mode and be sent. You can set this configuration option to false and there will be no codes except for when a ghost girl spawns. you dont need to set the bypasslist to empty at that point because it will not ever be bypassed.

And to answer the initial question, yes moons not listed in GGEbypasslist (with GGEbypass enabled) will only send codes when a ghost girl has spawned and is haunting someone. And again, you can also just disable GGEbypass to have the desired effect that codes will only be sent during hauntings.
